### ISSUE TITLE
기여 방법 질문 입니다.

### ISSUE THREAD

**Issue by thkwon1** [738/awesome-devbook#1]
질문 입니다 😄 

기여 방법에 대해서 따로 적혀있지 않은데,

```
1. 이슈등록 후 PR 생성
2. 선 PR 생성
```

`Q1. 1, 2번 중 편한 방법대로 하면 될까요??`

`Q2. 절판된 도서 여부는 상관없을 까요?`

**Comment by 738** [comment]
이슈 남겨주셔서 감사합니다.

`A1. 선 PR 생성 부탁드립니다.`

`A2. 넵 상관없습니다.`

기여 방법은 추후 `Contributing.md` 추가해서 작성하려고 합니다 👍 
기여 감사드려요 :)

**Comment by 738** [comment]
[`CONTRIBUTING.md`](https://github.com/738/awesome-devbook/blob/master/CONTRIBUTING.md) 생성했습니다.

**Comment by TaeHyoungKwon** [comment]
감사합니다 :)
