### ISSUE TITLE
리팩토링 | 코드 품질을 개선하는 객체지향 사고법 - 마틴 파울러 // 단종인것 같습니다.

### ISSUE THREAD

**Issue by syureu** [738/awesome-devbook#14]
클린코드
리팩토링 | 코드 품질을 개선하는 객체지향 사고법 - 마틴 파울러
https://book.naver.com/bookdb/book_detail.nhn?bid=7047630

위 책 book.naver에서 제휴가능한 온라인몰 안 나오는것 보아 단종인듯하고
아래에 2판이 있는듯 해서 특별한 사유가 없으면 개정판만 작성하면 되지않을까 싶습니다.

**Comment by 738** [comment]
제보 감사드립니다.

다만 1판(자바)과 2판(자바스크립트)은 매우 다른 책이라서 따로 표시해야할 필요는 있을것 같습니다.
절판되었다고 따로 표기하겠습니다 :)
